# Generated by Django 3.2.5 on 2021-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devisha',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=4)),
                ('dob', models.DateField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=12)),
                ('mail_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
