# Generated by Django 3.2.5 on 2021-07-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devisha', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devisha',
            new_name='Devi',
        ),
    ]
